public class AccountHelper {
   
   /* @invocableMethod
    public static void accountWebsiteUpdate(List<id> accIds) {
        system.debug('invocable method called. AccIds are : ' + accIds);
        List<account> listAccountToUpdate = new list<account>();
        for (Id eachId : accIds) {
            Account ac = new account();
            ac.Id = eachId; //ID setting is mandatory to update accounts
            ac.Website = 'www.yoll.io';
            listAccountToUpdate.add(ac);
        }
        update listAccountToUpdate;
    }*/
}