public  class AcTriggerHandler {
    //public static void TestTrigger(List<Account>acList) {
      //  for(Account ac: acList){
               //  contact ct = new contact(FirstName='Yannick', LastName='Carboro', AccountId= ac.id);
              //  insert ct;
              //  contact ct1 = new contact(FirstName='Bill', LastName='Morgan', AccountId= ac.id);
               // insert ct1;

//    }
}
//}