public class Calcu {
    integer a,b;

    public void accept(integer x, integer y){
        a = x;
        b = y;
    }

    public integer getSummation(){
        // integer i = a + b;
        // return i;
        return a+b;
    }

    public integer getDiffence(){
        // integer i = a + b;
        // return i;
        return a-b;
    }
    public integer getProduct(){
        // integer i = a + b;
        // return i;
        return a*b;
    }

    public integer getQuotient(){
        // integer i = a + b;
        // return i;
        return a/b;
    }

}