public class ControlFlow34 {
    public static void Practice(){
        integer a=19;
        integer g=69;
        boolean cl = true;
        if(a<18 || a>61){
            system.debug('Sorry! Out of Round 1');
            
        }else if(g<75){
            system.debug('Sorry! Out of Round 2');   
        }ELse if (cl=false) {
            system.debug('Sorry! Out of Round 3'); 
            
            
            
        }   ELSE{
            system.debug('Congratulations! You are Selected');
        } 
        
        
        
        
    }
    
}