public class ControlFlow32 {
    public static void practice() {
        
        Integer a=7 , b=8;
        If(a>b) {
            system.debug('First number is greater than second number.');
        }
        
        if(a<=b&a>=b){
            System.debug('Both numbers are same'); 
        }
        Else{
            system.debug('Second number is greater than first one');
            
        }
    }
}