public class DateWork{
public static void Practice(){
HW13OOP DateCal =new HW13OOP();

DateCal.setStartDate(date.newinstance(2019, 06, 14));
DateCal.setEndDate(date.newinstance(2023, 04, 20));

system.debug('Days betwwen= '+ DateCal.Daysbetweendates());
system.debug('Months betwwen= '+ DateCal.monthbetweendates());
system.debug('Start Date= '+Datecal.getStartDate());
system.debug('End Date= '+ Datecal.getEndDate());

}

}