public class DevHW3 {
public static void homew(){
String newMessage = 'Good Morning, Have a wonderful day!';
string message = 'Morning';
string message2 = 'afternoon';
string message3 = 'night';
string message4 = '?';
string message5 ='.';
string message6= '!';
Boolean result =newMessage.contains(message);
Boolean result2 =newMessage.contains(message2);
Boolean result3 =newMessage.contains(message3);
Boolean result4 =newMessage.contains(message4);
Boolean result5 =newMessage.contains(message5);
Boolean result6 =newMessage.contains(message6);
system.debug(result);
system.debug(result2);
system.debug(result3);
system.debug(result4);
system.debug(result5);
system.debug(result6);
    
    }
}