public class HalilHW2 {
    public static void Apexx261(){
        string name = 'Kral';
            system.debug ('Hey my name is' + name );
decimal xdx = 3.1415926535;
decimal xdx2 = xdx.setScale(2);
decimal xdx3 = xdx.setScale(3);
decimal xdx4 = xdx.setScale(4);
decimal xdx5 = xdx.setScale(5);

        
system.debug('Values of pi is' + xdx);
system.debug('Value of pi is' + xdx2);
system.debug('Values of pi is' + xdx3);
system.debug('Values of pi is' + xdx4);
system.debug('Values of pi is' + xdx5);
        
    
    }
   }