public class hm {
    public static void hm() {

     string name1='Samantha';
     string name2='Dave';
     string name3='Eli';
     string userInput1 = name1;
    string userinput2 = name2;
      string userinput3 = name3;
        integer a = userInput1.length();
        integer b = userInput2.length();
        integer c = userInput3.length();
    
    
        string aa = userinput1.substring(a-4, a);
        string bb = userinput2.substring(b-4, b);
        string cc = userinput3.substring(c-4, c);
        
       
        
        
        
        integer len1= aa.length();
        integer len2= bb.length();
        integer len3= cc.length();
        
        

        
        
        
      Integer x = len1 > 3  ? len3 : 3;
        
        system.debug(len1>3 && len2 >3);
        
        
            
        

    
    }

}