public virtual class HomeW15OOP {
   integer var1;
   string var2;
   List<integer>List1;
     public integer getVar1(){
        return var1;
     }
     public string getVar2(){
        return var2;
     }
    public list<integer> getList1(){
        return list1;
    }
    public void setVar1(integer var1){
     this.var1=var1;
    }
    public void setVar2(string var2){
        this.var2=var2;
    }
    public void setList1(List<integer>List1){
        this.list1=list1;
    }
    
    

}