public with sharing class HW13OOP {
    Date startDate;
    Date endDate;
  
    public date getStartDate() {
return startDate;
    }
public void setStartDate(date sd){
this.startDate=sd;
}
public date getEndDate() {
    return endDate;
        }
    public void setEndDate(date ed){
    this.endDate=ed;
    }
    public integer Daysbetweendates(){
        integer diff1=  startDate.daysbetween(endDate);
       
       return  startDate.daysbetween(endDate);
     
     }
     public integer  monthbetweendates(){
      integer diff2= startDate.monthsBetween(endDate);
     
         return  startDate.monthsBetween(endDate);
     
     }
    
    
    
    
    }
