public class HW15Program {
    public static void show() {
HomeW15OOP Parent= new HomeW15OOP();
Parent.setVar1(34);
Parent.setVar2('Istanbul');
Parent.setList1(new List<integer> {10, 20, 30});
System.debug('My area code is= ' +Parent.getVar1());
System.debug('I am from= ' +Parent.getVar2());
Child1 c1= new Child1();
c1.setVar3(37.5);
child2 c2=new child2();
c2.setSet1(new set<integer> {5,15,25});

}
}