public  class HW2OOP {
   String vin;
   string company;
   string model;
   Integer Year;
   String Color;
   Decimal Price;

    public void show() {
vin='JMKA243MK454';
company='Toyota' ;
model='Corolla';
Year= 2020;
color='Blue';
Price=19500.00;
system.debug('VIN Number= '+ vin);
system.debug('Brand= '+company);
system.debug('Model= '+model);
system.debug('Year= ' + year);
system.debug('Color= ' + color);
system.debug('MSRP= '+ price);

}
}