public  class HW4OOP {
    String admNo;
    String stuName;
    List<decimal> Marks = new list<decimal>();
    
    
    public void accept(string aNo, string sdtn,list<decimal>mrk) {
        admNo=aNo;
        stuName=sdtn;
        marks=mrk;

}
public string getStudentNo(){

    return admNo;
}
public string getSName(){
return stuName;

}
public list<decimal> getMarks(){

    return marks;
}




}