
    public class HW7OOP2{
        public static void show(){
        HW7OOP PersonProgram = new HW7OOP();
        PersonProgram.accept('Sergio','Oliviera',28);
        string fullName= PersonProgram.getName();
        system.debug('Full Name= '+ fullName);
        
        integer Age =PersonProgram.getAge();
        system.debug('Age= '+ age);
        
        PersonProgram.accept2('Lucas','Torreira',27);
        string fullName2= PersonProgram.getName2();
        system.debug('Full Name= '+ fullName2);
        
        integer Agee =PersonProgram.getAge2();
        system.debug('Age= '+ agee);
        
        
        }
        
        
        
        
        }