public class HW8CAR {
    String company;
    String model;
    Integer mfgYear;
    Decimal price;
public void accept(string company1,String model1,Integer mfgYear1,Decimal price1 ){
    company=company1;
    model=model1;
    mfgYear=mfgYear1;
    price=price1;

}

public void accept2(string company2,String model2,Integer mfgYear2,Decimal price2 ){
company=company2;
model=model2;
mfgYear=mfgYear2;
price=price2;
}
public string getCompany1(){
    return company;
}
public string getModel1(){
    return Model;
}
public integer getMfgYear1(){
    return mfgYear;
}
public decimal price1(){
return price;
}
public string getCompany2(){
return company;
}  
public string getModel2(){
return Model;
}
public integer getMfgYear2(){
return mfgYear;
}
public decimal price2(){
return price;
}


}
