public class HW9OOP2 {
    public static void SalaryCal() {
        HW9OOP ES = new HW9OOP();
        Es.accept('1071' ,'Alisson Becker', 12000.00);
        decimal g= es.getGrossSalary();
        decimal n=es.netSalary();
        system.debug('Employee Code= '+Es.getEmployeeCode() );
        system.debug('Employee Name= '+es.getEmployeeName() );
        system.debug('Gross Salary= '+ g.setscale(2));
        system.debug('Net Salary= '+n.setscale(2));
    

    }
}