public class LoopClass {
    public static void practice(){

        
  ///      integer countEven =0;
     ///   integer countOdd= 0;
        ///for(integer i =0; i<10 ; i++){
           // if(math.mod(i,2)==0){ 
            //system.debug('I can count even' + i);
            //countEven++;
        //}
       // }
      //  system.debug('Total even numbers printed here');
        

/*
integer a= 5;
integer total=0;
for(integer i=0; i<4; i++){
    total +=a;
}
system.debug(total); //*
    }
}    
*/
        
 /*       
        integer a = 1;
        integer cd = 2;
        string series= ' ';
        for(integer t=1; t<=5; t++) {
            series += a + ', ';
            a+=cd;
        }
        system.debug(series);
        }
}
*/
        
        integer term= 12;
       integer f= ++term;
        
        for(integer a= 0;a<=12; a++) {
           
        }
            system.debug(term+=f);
            }
}