public class lopp {
   /* public static void practice(){
        
        integer x = 7457;
        integer ReverseX=0;
        integer xx= x;
        while(x > 0){
            
            
            ReverseX = ReverseX*10;
            ReverseX += math.mod(x,10);  
            
            
            x = x/10; 
            
            
        }
        If(xx==x){
            system.debug(Reversex + 'is Palindrome number');
        }
        Else{
            system.debug(Reversex + 'is not Palindrome number');
        }
    }

	public static void practice3(){
        integer j = 1;
        integer x= 0;
        
        do{
            x+=j;
            j++;
           
        } while(j <=10);
        system.debug(x);
    }
}*/
    
/*    
        
        integer FV = 1;
        integer CD= 3;
        integer T=5;
        
        
        do{
            system.debug(FV);
            fv=+cd;
            fv++;
            
        } while(fv <=t);
        system.debug(cd); */
    public static void practice3(){   
    
    /*for(integer leg= 1; leg <=4; leg++){
        system.debug('we are assembling leg #' + leg);
        
        for(integer screw = 1; screw <=3; screw++){
            system.debug('tightning screw #' + screw +'for leg #' +leg); 
        
        }
           
    }*/
    
        for(integer i=1; i<=5; i++){
            string str= ' ';
            for(integer j=1; j<=i ;j++){
       str+= ('*');
        }
        system.debug(str);
                }
    }
    
    }