public class Module {
    public static void Module3s(){ 
        integer a = 2;
        
        switch on a {
   when 2 {
       System.debug('TWO');
   }
      when 4 {
       System.debug('FOUR');
   }
       when -3 {
       System.debug('EROOR: Invalid Single Digit Number');
   }
   when else {
       System.debug('EROOR: Invalid Single Digit Number');
   }
}
        
   
        
        
       
 
    
    }

            }