public virtual class OldEmployeeClass {
   string empCode;
   string empName;
   decimal salary;
   public string getCode(){
    return empCode;
 }
 public string getName(){
    return empName;
 }
   public decimal getSalary(){
    return Salary;
   }
   public void setCode(string empCode){
    this.empCode=empCode;
   }
   public void setName(string empName){
    this.empName=empName;
   }
  public void setSalary(decimal salary){
    this.Salary=Salary;
  }
}