public class SetDemo1 {
    public static void citySet() {
        Set<String> cities = new set<string>();
        cities.add('Tokyo');
        cities.add('Berlin');
        cities.add('Nairobi');
        cities.add('Lisbon');
        cities.add('Tokyo');
        cities.add('Lisbon');
        cities.add('TOKYO');
        system.debug(cities);
    }
    public static void setOfList() {
        //set of list of integer.
        set<list<integer>> setOfListInt = new set<list<integer>>();
        list<integer> list1 = new list<integer>{1,3,5,7,9, 1, 3 , 7};
        list<integer> list2 = new list<integer>{10,20,30,70,90};
        list<integer> list3 = new list<integer>{11,33,55,77,99};

        setOfListInt.add(list1);
        setOfListInt.add(list2);
        setOfListInt.add(list3);
        setOfListInt.add(new list<integer>{1,3,5,7,9});
        setOfListInt.add(new list<integer>{10,20,30,70,90});
        system.debug(setOfListInt);
    }

public static void Assigment5



} 


