public class StringMethodDemo {
    public static void practice () {
       /* system.debug('we will practice string methods');
        string firstString = 'vital is learning string methods';
           system.debug( '1' + firstString);
           firstString = firstString.capitalize();
        system.debug ( '2' + firstString.capitalize());
            system.debug( '3' +firstString);
          */  
/*  string word = 'apex';
      system.debug('1,' + word.isAllLowerCase());
        system.debug('1,' + word.isAllUpperCase());
        word = 'APEX';
        system.debug('1,' + word.isAllLowerCase());
        system.debug('1,' + word.isAllUpperCase());
        string word2= 'Apex';
        system.debug('1,' + word2.isAllLowerCase());
        system.debug('1,' + word2.isAllUpperCase());
        */
  STRINg sentence = 'we are learning apex, and its fun';
        string word = 'fun';
        boolean check1 = sentence.contains(word);
        system.debug(check1); 
        
        
    
        
    
    }
    
}