public class StringMethodsDemo {
    public static void practice(){
        system.debug('we will practice string methods');
        
        string firstString = 'vitap is learning string methods';
        system.debug('1' + firstString);
        firstString = firstString.capitalize();
        system.debug('2' + firstString.capitalize());
        system.debug('3' + firstString);
        
        
        /*
        //2.
        string word = 'apex';
        system.debug('1, ' + word.isAllLowerCase()); //true
        system.debug('1, ' + word.isAllUpperCase()); //false
        word = 'APEX';
        system.debug('2' + word.isAllLowerCase()); //false
        system.debug('2' + word.isAllUpperCase()); //true
        string word2 = 'Apex';
        system.debug('3' + word2.isAllLowerCase()); //false
        system.debug('3' + word2.isAllUpperCase()); //false
        
        //2.1
        string pwd = 'ADMIN';
        boolean pwdUpperCase = pwd.isAllUpperCase();
        system.debug(pwdUppercase);
        system.debug(pwd.isAllLowerCase());
        
        //2.2
        string sentence = 'APEX';
        system.debug('5 ' + sentence.isAllLowerCase()); //
        system.debug('5 ' + sentence.isAllUpperCase()); //
		
        STRINg sentence = 'we are learning apex, and its fun';
        string word = 'Fun';
        boolean check1 = sentence.contains(word);
        system.debug(check1); //false
        
        //4
        boolean check2 = sentence.containsIgnoreCase(word);
        system.debug(check2); //true
    
        //5.equals
        string ok = 'OKAY';
        
        string ok2 = 'not okay';
        string ok3 = 'okay';
        string ok4 = 'OKAY';
        
    	system.debug(ok.equals(ok2)); //false
        system.debug(ok.equals(ok3)); // false
		system.debug(ok.equals(ok4)); //  true    
        
        //why and when do we create variable?
        //if we want to reuse it again and again in our code, then we create variables.
        
        system.debug('ignore case ' + ok.equalsIgnoreCase(ok2)); //false
        system.debug('ignore case ' + ok.equalsIgnoreCase(ok3)); // true
        system.debug('ignore case ' + ok.equalsIgnoreCase(ok4)); // true
    
    
        string str = 'i like to travel';
        string str2 = 'i like to travel';
        
        system.debug('sentence check' + str.equals(str2));
        
    
    
    
    
    
    
    
    }
    
    public static void practice2(){
        string comment = 'black magic!';
        				//012345....	
        string word1 = 'k';
        integer indexOfK1 = comment.indexOf(word1); //
        integer indexOfK2 = comment.indexOf('k');   //
        system.debug('index Of K 1 ' + indexOfK1);
        system.debug('index Of K 2 ' + indexOfK2);
        */
        
      
     string text1 = 'Salesforce use APEX as a Programming Language';
            string text2 = 'Salesforce';
                string text3 =  'Apex';
                
        
        
   
        
    
    }
}